version: '3.8'

services:
  ocr-backend:
    build: 
      context: .
      dockerfile: Dockerfile-light
    container_name: ocr-backend-simple
    ports:
      - "8001:5000"
    environment:
      - FLASK_ENV=production
      - MAX_CONTENT_LENGTH=50000000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ocr-simple-network