version: '3.8'

services:
  ocr-backend:
    build: 
      context: .
      dockerfile: Dockerfile-light
    container_name: ocr-backend-light
    ports:
      - "8001:5000"
    environment:
      - FLASK_ENV=production
      - MAX_CONTENT_LENGTH=50000000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    restart: unless-stopped
    # LÍMITES DE MEMORIA MUY ESTRICTOS
    deploy:
      resources:
        limits:
          memory: 1G        # Máximo 1GB
          cpus: '1.0'       # 1 CPU
        reservations:
          memory: 256M      # Mínimo 256MB
          cpus: '0.5'       # 0.5 CPU
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ocr-light-network